### ISSUE TITLE
zipfile Removed from pip3

### ISSUE THREAD

**Issue by swarupsro** [EngineerDanny/apk-framework-detector#1]
Dear Concern,
I encountered a problem installing it.

![image](https://user-images.githubusercontent.com/7780919/173159975-43cd1f71-a5dd-4226-9900-5927aca955f7.png)

**Comment by EngineerDanny** [comment]
Which zipfile version did you install?

**Comment by rew1nter** [comment]
You basically can't install this. It was removed.

**Comment by EngineerDanny** [comment]
Could you submit a pull request?
