### ISSUE TITLE
ERROR: Could not open requirements file

### ISSUE THREAD

**Issue by Brumanuel** [EngineerDanny/apk-framework-detector#4]
Hi,
 
Following the instructions, in the step of installing dependencies, I receive the following error:

pip install -r requirements.txt` or  `pip3 install -r requirements.txt
ERROR: Could not open requirements file: [Errno 2] No existe el archivo o el directorio: 'requirements.txt'

I'm not familiar with Python projects, I'm not sure if I'm doing something wrong.

**Comment by EngineerDanny** [comment]
I have updated the README.md file.
Now you only need to run this:
`pip install zipfile36`

I hope it helps with your issue.

**Comment by Brumanuel** [comment]
Thanks! works fine!
